SELECT YEAR, (b.MAX_COLONY-a.SIZE_OF_COLONY) AS YEAR_DEV, a.ID
FROM ECOLI_DATA a
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) b ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC