-- 코드를 작성해주세요
# SELECT AVG(COALESCE(LENGTH,10)) AS AVG_LENGTH,FISH_TYPE,COUNT(*) AS FISH_COUNT
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# HAVING AVG(COALESCE(LENGTH,10)) >= 33

# SELECT b.FISH_COUNT,a.Length AS MAX_LENGTH,a.FISH_TYPE
SELECT b.FISH_COUNT,MAX(a.LENGTH) AS MAX_LENGTH, a.FISH_TYPE
FROM FISH_INFO a
JOIN (
    SELECT AVG(COALESCE(LENGTH,10)) AS AVG_LENGTH,FISH_TYPE,COUNT(*) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(COALESCE(LENGTH,10)) >= 33
) b ON a.FISH_TYPE = b.FISH_TYPE
GROUP BY b.FISH_TYPE, b.AVG_LENGTH, b.FISH_COUNT
ORDER BY a.FISH_TYPE
# GROUP BY a.FISH_TYPE
# HAVING MAX(a.LENGTH)
# ORDER BY a.FISH_TYPE
# ORDER BY LENGTH DESC
# LIMIT 1